//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceTrackingBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class facial_data
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> nose_angle_1 { get; set; }
        public Nullable<decimal> forehead_length_1 { get; set; }
    }
}
